language: bash
services: docker

env:
  global:
    - REPO_NAME=norby/php-alpine
  matrix:
    - BASE_IMAGE=fpm-alpine VERSION=7.1 EXTRA_TAGS="7.1-fpm"
    - BASE_IMAGE=cli-alpine VERSION=7.1 EXTRA_TAGS="7.1-cli"
    - BASE_IMAGE=fpm-alpine VERSION=7.2 EXTRA_TAGS="7.2-fpm"
    - BASE_IMAGE=cli-alpine VERSION=7.2 EXTRA_TAGS="7.2-cli"
    - BASE_IMAGE=fpm-alpine VERSION=7.3 EXTRA_TAGS="7.3-fpm"
    - BASE_IMAGE=cli-alpine VERSION=7.3 EXTRA_TAGS="7.3-cli"
    - BASE_IMAGE=fpm-alpine VERSION=7.4 EXTRA_TAGS="latest-fpm;7.4-fpm"
    - BASE_IMAGE=cli-alpine VERSION=7.4 EXTRA_TAGS="latest-cli;7.4-cli"

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - "./hooks/build.sh"

after_script:
  - docker images