language: bash
services: docker

env:
  global:
    - REPO_NAME=norby/php
  matrix:
    - VERSION=7.1 EXTRA_TAGS="7.1-fpm-alpine"
    - VERSION=7.2 EXTRA_TAGS="latest-fpm-alpine; 7.2-fpm-alpine"

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - "./hooks/build.sh"

after_script:
  - docker images