language: bash
services: docker

env:
  global:
    - REPO_NAME=norby/php-alpine
  matrix:
    - BASE_IMAGE=fpm-alpine VERSION=7.1 EXTRA_TAGS="7.1-fpm"
    - BASE_IMAGE=cli-alpine VERSION=7.1 EXTRA_TAGS="7.1-cli"
    - BASE_IMAGE=fpm-alpine VERSION=7.2 EXTRA_TAGS="7.2-fpm"
    - BASE_IMAGE=cli-alpine VERSION=7.2 EXTRA_TAGS="7.2-cli"
    - BASE_IMAGE=fpm-alpine VERSION=7.3 EXTRA_TAGS="7.3-fpm"
    - BASE_IMAGE=cli-alpine VERSION=7.3 EXTRA_TAGS="7.3-cli"
    - BASE_IMAGE=fpm-alpine VERSION=7.4 EXTRA_TAGS="7.4-fpm"
    - BASE_IMAGE=cli-alpine VERSION=7.4 EXTRA_TAGS="7.4-cli"
    - BASE_IMAGE=fpm-alpine VERSION=8.0 EXTRA_TAGS="8.0-fpm"
    - BASE_IMAGE=cli-alpine VERSION=8.0 EXTRA_TAGS="8.0-cli"
    - BASE_IMAGE=fpm-alpine VERSION=8.1 EXTRA_TAGS="latest-fpm;8.1-fpm"
    - BASE_IMAGE=cli-alpine VERSION=8.1 EXTRA_TAGS="latest-cli;8.1-cli"

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - "./hooks/build.sh"

after_script:
  - docker images