#!/bin/bash

set -ex

# Don't push images if branch is not master
echo "Current Branch: $SOURCE_BRANCH"
if [ "${SOURCE_BRANCH}" != "master" ]; then
    exit 0
fi

for tag in $(sudo docker images $REPO_NAME --format "{{.Tag}}");
do
    docker push "${REPO_NAME}:${tag}"
done